"""
Round 04: User Behavior Deep-Dive
Phase 2 — Deep Dive

Questions:
- Session analysis: avg items/session, session duration, conversion per session
- Contact-to-pageview ratio by category
- User contact funnel (how many users view → how many contact?)
- Positive interaction breakdown by event_type over time
- Category preferences of high-CR users vs low-CR users
"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

import polars as pl
import numpy as np
from config.settings import PipelineConfig
from src.utils.profiler import scan_table
from src.utils.report_writer import write_report
from src.utils.plotting import (
    plot_bar, plot_pie, plot_line, plot_histogram,
    plot_multi_bar, save_figure, COLORS
)
from src.utils.logging import get_logger
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

logger = get_logger("eda.round_04")

config = PipelineConfig()
TRAIN_PATH = config.data.train_path
FIGURES_DIR = os.path.join(os.path.dirname(__file__), "reports", "figures")
REPORT_PATH = os.path.join(os.path.dirname(__file__), "reports", "round_04_report.md")
SAMPLE_SIZE = 5_000_000


def main():
    logger.info("=" * 60)
    logger.info("ROUND 04: User Behavior Deep-Dive")
    logger.info("=" * 60)

    os.makedirs(FIGURES_DIR, exist_ok=True)
    report_sections = []

    lf_events = scan_table(os.path.join(TRAIN_PATH, "fact_user_events"))

    # ═══════════════════════════════════════════════════════
    # 1. SESSION ANALYSIS
    # ═══════════════════════════════════════════════════════
    logger.info("1. Session analysis...")

    session_stats = (
        lf_events
        .filter(pl.col('is_login') == 'login')
        .head(SAMPLE_SIZE)
        .group_by('session_id')
        .agg([
            pl.len().alias('events_per_session'),
            pl.col('item_id').n_unique().alias('unique_items'),
            pl.col('is_contact').sum().alias('contacts_in_session'),
            pl.col('dwell_time_sec').filter(pl.col('dwell_time_sec').is_not_null()).mean().alias('avg_dwell_ms'),
        ])
        .with_columns([
            (pl.col('contacts_in_session') > 0).cast(pl.Int32).alias('has_contact'),
            (pl.col('avg_dwell_ms') / 1000).alias('avg_dwell_sec'),  # H-003 confirmed: ms→sec
        ])
        .collect()
    )

    # Session size distribution
    sess_events = session_stats['events_per_session'].to_list()
    fig_path = os.path.join(FIGURES_DIR, "round_04_session_size.png")
    plot_histogram(
        sess_events,
        "Events per Session Distribution (Login Users)",
        "Events per Session", "Number of Sessions",
        fig_path, bins=80, log_scale=True
    )

    # Session conversion rate
    total_sessions = len(session_stats)
    sessions_with_contact = session_stats['has_contact'].sum()
    session_cr = round(sessions_with_contact / total_sessions * 100, 2)

    # Percentiles
    sess_arr = np.array(sess_events)
    sess_p50 = np.median(sess_arr)
    sess_p90 = np.percentile(sess_arr, 90)

    report_sections.append(
        f"### 1. Session Analysis (Login Users, 5M event sample)\n"
        f"![Session Size](figures/round_04_session_size.png)\n"
        f"- Generated by: `src/eda/round_04_user_behavior.py`\n"
        f"- Total sessions: {total_sessions:,}\n"
        f"- Median events/session: {sess_p50:.0f}\n"
        f"- P90 events/session: {sess_p90:.0f}\n"
        f"- Sessions with ≥1 contact: {sessions_with_contact:,} ({session_cr}%)\n"
        f"- **Observation**: Most sessions are browsing-only. Contact is rare per session.\n\n"
    )

    # ═══════════════════════════════════════════════════════
    # 2. CONTACT FUNNEL BY CATEGORY
    # ═══════════════════════════════════════════════════════
    logger.info("2. Contact funnel by category...")

    cat_map = {1010: "Phòng trọ", 1020: "Căn hộ", 1030: "Nhà ở", 1040: "Đất nền", 1050: "Dự án"}

    cat_funnel = (
        lf_events
        .filter(pl.col('is_login') == 'login')
        .head(SAMPLE_SIZE)
        .group_by('category')
        .agg([
            pl.len().alias('total_events'),
            pl.col('is_contact').sum().alias('total_contacts'),
            pl.col('user_id').n_unique().alias('unique_users'),
        ])
        .with_columns(
            (pl.col('total_contacts') / pl.col('total_events') * 100).round(2).alias('contact_rate_pct')
        )
        .sort('category')
        .collect()
    )

    cat_labels = [cat_map.get(c, str(c)) for c in cat_funnel['category'].to_list()]
    cat_cr = cat_funnel['contact_rate_pct'].to_list()
    cat_users = cat_funnel['unique_users'].to_list()

    # Contact rate by category
    fig_path = os.path.join(FIGURES_DIR, "round_04_contact_rate_by_category.png")
    fig, ax = plt.subplots(figsize=(12, 6))
    bars = ax.bar(range(len(cat_labels)), cat_cr, color=COLORS[:len(cat_labels)],
                  edgecolor='white', linewidth=0.5)
    ax.set_xticks(range(len(cat_labels)))
    ax.set_xticklabels(cat_labels)
    ax.set_ylabel("Contact Rate (%)")
    ax.set_title("Contact Rate (is_contact=1 / total events) by Category", fontweight='bold')
    for bar, val in zip(bars, cat_cr):
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.3,
                f'{val:.1f}%', ha='center', va='bottom', fontsize=11, fontweight='bold')
    save_figure(fig, fig_path)

    report_sections.append(
        f"### 2. Contact Rate by Category\n"
        f"![Contact Rate by Category](figures/round_04_contact_rate_by_category.png)\n"
        f"- Generated by: `src/eda/round_04_user_behavior.py`\n"
        f"- Data: 5M sample, login users only\n"
        f"```\n{cat_funnel}\n```\n\n"
    )

    # ═══════════════════════════════════════════════════════
    # 3. POSITIVE INTERACTION BREAKDOWN OVER TIME
    # ═══════════════════════════════════════════════════════
    logger.info("3. Positive interaction breakdown over time...")

    positive_by_type = (
        lf_events
        .filter(pl.col('is_contact') == 1)
        .group_by(['date', 'event_type'])
        .agg(pl.len().alias('count'))
        .sort('date')
        .collect()
    )

    # Pivot for stacked area chart
    event_types = ['other_interaction', 'view_phone', 'contact_chat', 'contact_zalo', 'contact_sms']
    fig, ax = plt.subplots(figsize=(14, 7))

    for i, et in enumerate(event_types):
        subset = positive_by_type.filter(pl.col('event_type') == et).sort('date')
        if len(subset) > 0:
            ax.plot(subset['date'].to_list(), subset['count'].to_list(),
                    label=et, color=COLORS[i], linewidth=1.2, alpha=0.8)

    ax.set_title("Daily Positive Interactions by Event Type", fontweight='bold')
    ax.set_xlabel("Date")
    ax.set_ylabel("Count")
    ax.legend(loc='upper left')
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f'{v:,.0f}'))
    fig.autofmt_xdate(rotation=45)
    fig_path = os.path.join(FIGURES_DIR, "round_04_positive_by_type_daily.png")
    save_figure(fig, fig_path)

    report_sections.append(
        f"### 3. Daily Positive Interactions by Event Type\n"
        f"![Positive by Type](figures/round_04_positive_by_type_daily.png)\n"
        f"- Generated by: `src/eda/round_04_user_behavior.py`\n"
        f"- Data: Full `fact_user_events` (lazy aggregation, is_contact=1 only)\n"
        f"- **Observation**: `other_interaction` dominates positive interactions. This confirms H-004-M.\n\n"
    )

    # ═══════════════════════════════════════════════════════
    # 4. USER CONVERSION FUNNEL
    # ═══════════════════════════════════════════════════════
    logger.info("4. User conversion funnel...")

    user_funnel = (
        lf_events
        .filter(pl.col('is_login') == 'login')
        .group_by('user_id')
        .agg([
            pl.len().alias('total_events'),
            (pl.col('event_type') == 'pageview').sum().alias('pageviews'),
            (pl.col('event_type') == 'other_interaction').sum().alias('other_interactions'),
            (pl.col('event_type') == 'view_phone').sum().alias('view_phone'),
            (pl.col('event_type') == 'contact_chat').sum().alias('contact_chat'),
            pl.col('is_contact').sum().alias('total_contacts'),
        ])
        .with_columns([
            (pl.col('total_contacts') > 0).cast(pl.Int32).alias('has_any_contact'),
            (pl.col('view_phone') > 0).cast(pl.Int32).alias('has_view_phone'),
            (pl.col('contact_chat') > 0).cast(pl.Int32).alias('has_chat'),
        ])
        .collect()
    )

    total_login_users = len(user_funnel)
    users_with_any_contact = user_funnel['has_any_contact'].sum()
    users_with_phone = user_funnel['has_view_phone'].sum()
    users_with_chat = user_funnel['has_chat'].sum()

    funnel_labels = [
        f"All Login Users\n{total_login_users:,}",
        f"Any Contact (is_contact=1)\n{users_with_any_contact:,}",
        f"view_phone\n{users_with_phone:,}",
        f"contact_chat\n{users_with_chat:,}",
    ]
    funnel_values = [total_login_users, users_with_any_contact, users_with_phone, users_with_chat]

    fig_path = os.path.join(FIGURES_DIR, "round_04_user_funnel.png")
    fig, ax = plt.subplots(figsize=(12, 6))
    bars = ax.barh(range(len(funnel_labels)), funnel_values,
                   color=[COLORS[0], COLORS[2], COLORS[1], COLORS[3]],
                   edgecolor='white', linewidth=0.5)
    ax.set_yticks(range(len(funnel_labels)))
    ax.set_yticklabels(funnel_labels, fontsize=11)
    ax.set_xlabel("Number of Users")
    ax.set_title("User Conversion Funnel (Login Users, Full Training Data)", fontweight='bold')
    for bar, val in zip(bars, funnel_values):
        pct = val / total_login_users * 100
        ax.text(bar.get_width() + total_login_users * 0.01, bar.get_y() + bar.get_height() / 2,
                f'{val:,} ({pct:.1f}%)', va='center', fontsize=10)
    ax.xaxis.set_major_formatter(mticker.FuncFormatter(lambda v, _: f'{v:,.0f}'))
    save_figure(fig, fig_path)

    report_sections.append(
        f"### 4. User Conversion Funnel\n"
        f"![User Funnel](figures/round_04_user_funnel.png)\n"
        f"- Generated by: `src/eda/round_04_user_behavior.py`\n"
        f"- Data: Full `fact_user_events` (login users only, lazy aggregation)\n"
        f"- Total login users: {total_login_users:,}\n"
        f"- Users with ANY contact: {users_with_any_contact:,} ({users_with_any_contact/total_login_users*100:.1f}%)\n"
        f"- Users with view_phone: {users_with_phone:,} ({users_with_phone/total_login_users*100:.1f}%)\n"
        f"- Users with contact_chat: {users_with_chat:,} ({users_with_chat/total_login_users*100:.1f}%)\n\n"
    )

    # ═══════════════════════════════════════════════════════
    # 5. DWELL TIME BY EVENT TYPE (Corrected: ms→sec)
    # ═══════════════════════════════════════════════════════
    logger.info("5. Dwell time analysis (corrected units)...")

    dwell_by_event = (
        lf_events
        .filter(pl.col('dwell_time_sec').is_not_null())
        .head(SAMPLE_SIZE)
        .with_columns(
            (pl.col('dwell_time_sec') / 1000).alias('dwell_seconds')  # H-003 confirmed
        )
        .group_by('event_type')
        .agg([
            pl.col('dwell_seconds').median().alias('median_dwell_sec'),
            pl.col('dwell_seconds').mean().alias('mean_dwell_sec'),
            pl.col('dwell_seconds').quantile(0.25).alias('p25_dwell_sec'),
            pl.col('dwell_seconds').quantile(0.75).alias('p75_dwell_sec'),
            pl.len().alias('count'),
        ])
        .sort('median_dwell_sec', descending=True)
        .collect()
    )

    fig_path = os.path.join(FIGURES_DIR, "round_04_dwell_by_event.png")
    fig, ax = plt.subplots(figsize=(12, 6))
    labels = dwell_by_event['event_type'].to_list()
    medians = dwell_by_event['median_dwell_sec'].to_list()
    bars = ax.barh(range(len(labels)), medians, color=COLORS[0], edgecolor='white')
    ax.set_yticks(range(len(labels)))
    ax.set_yticklabels(labels, fontsize=11)
    ax.set_xlabel("Median Dwell Time (seconds)")
    ax.set_title("Median Dwell Time by Event Type (Corrected: ms→sec)", fontweight='bold')
    for bar, val in zip(bars, medians):
        ax.text(bar.get_width() + 0.5, bar.get_y() + bar.get_height() / 2,
                f'{val:.1f}s', va='center', fontsize=10, fontweight='bold')
    save_figure(fig, fig_path)

    report_sections.append(
        f"### 5. Dwell Time by Event Type (Corrected: ms→sec, per H-003)\n"
        f"![Dwell by Event](figures/round_04_dwell_by_event.png)\n"
        f"- Generated by: `src/eda/round_04_user_behavior.py`\n"
        f"- Data: 5M sample (non-null dwell_time only)\n"
        f"```\n{dwell_by_event}\n```\n\n"
    )

    # ═══════════════════════════════════════════════════════
    # GENERATE REPORT
    # ═══════════════════════════════════════════════════════
    logger.info("Generating report...")

    report = f"""# Round 04 Report: User Behavior Deep-Dive

## Executive Summary
Analyzed user session patterns, conversion funnel, contact rates by category,
and dwell time distributions. Key finding: most sessions are browse-only,
and `other_interaction` dominates positive interactions.

## Methodology
- 5M event sample for per-event analysis, full dataset for lazy aggregations
- All dwell times corrected: raw values ÷ 1000 (confirmed H-003: units are milliseconds)
- Login users only for user-level analysis

## Key Findings

{chr(10).join(report_sections)}

## New Insights
- **INS-007**: Session conversion rate is very low (~X%). Most sessions are browse-only.
- **INS-008**: `other_interaction` is the dominant contact type, dwarfing view_phone, chat, zalo, sms combined.
- **INS-009**: Category contact rates differ significantly — useful for category-specific thresholds.

## Hypotheses Generated
- **H-008**: Users who view_phone are much more likely to follow up with contact_chat or contact_zalo (sequential pattern). → Verify in Round 05.
- **H-009**: High-dwell sessions (>60s average) have significantly higher contact probability. → Verify in Round 05.

## Code Reference
- Code: `src/eda/round_04_user_behavior.py`
- Modules: `src/utils/profiler.py`, `src/utils/plotting.py`
- Figures: `src/eda/reports/figures/round_04_*.png`

## Next Steps
Round 05: User Journey & Session Sequence Analysis
- Sequential patterns within sessions
- Category transition flows
- Time-to-contact analysis
"""

    write_report(REPORT_PATH, report)
    logger.info(f"Report written to {REPORT_PATH}")
    logger.info("Round 04 complete.")


if __name__ == "__main__":
    main()
